### ISSUE TITLE
Remove usage of create_function() - PHP 7.2+ compatibility

### ISSUE THREAD

**Issue by cjg89** [UCF/WP-Allowed-Hosts#1]
`create_function()` was deprecated as of PHP 7.2.  Instances of this this function throughout the repo should be removed and replaced with anonymous functions to support newer versions of PHP.

See https://www.php.net/manual/en/function.create-function.php

**Comment by cjg89** [comment]
Resolved in v1.0.6.

**Comment by timwsuqld** [comment]
@cjg89 Is this going to be released at https://wordpress.org/plugins/wp-allow-hosts or somewhere else? Thanks

**Comment by cjg89** [comment]
Hey @timwsuqld, we (finally) have the latest version of this plugin deployed to the WordPress plugin repository as of today: https://wordpress.org/plugins/wp-allow-hosts
