### ISSUE TITLE
Lastest tagged version not published on Wordpress Plugin Repository

### ISSUE THREAD

**Issue by timwsuqld** [UCF/WP-Allowed-Hosts#3]
The latest tag hasn't been pushed to the wordpress plugin repository. This makes it impossible for people to get automatic updates, as they can only do manual upgrades by downloading a zip from here.

**Comment by cjg89** [comment]
This was also noted here https://github.com/UCF/WP-Allowed-Hosts/issues/1#issuecomment-515042387, but this has been resolved.
